#ifndef MINIZ_CONFIG_HOST_H
#define MINIZ_CONFIG_HOST_H

#define MINIZ_NO_STDIO
#define MINIZ_NO_TIME
#define MINIZ_NO_ARCHIVE_APIS
#define MINIZ_NO_ARCHIVE_WRITING_APIS
#define MINIZ_NO_ZLIB_COMPATIBLE_NAMES

#endif // MINIZ_CONFIG_HOST_H
